<?php
/**
* Implementation of consultation_ressources().
*/
function consultation_ressources_block_info(){
	$blocks = array(); 
	$blocks['consultation_ressources'] = array(
		'info' => t("Consultation des ressources."),
		'cache' => DRUPAL_NO_CACHE,
		);
	return $blocks;
}

function consultation_ressources_permission() {
  return array('access consultation_ressources' => array('title' => t('Accès Consultation Ressources')));
}

function consultation_ressources_block_view($block_name=''){
	
	$block = array();

	switch ($block_name) {
		case 'consultation_ressources':
			$block['subject'] = t('Consulter des ressources');
			$block['content'] = consultation_ressources_listing();
			break;
	}

	return $block;
}

function consultation_ressources_init(){

}

function consultation_ressources_listing(){
	drupal_add_css(drupal_get_path('module', 'consultation_ressources') . '/css/styleConsultationRessources.css');
	if(user_access('access consultation_rapport_de_stage')){
		$tableauHTML = '<table>
							<tr><th>nom</th></tr>
							<tr><td>test</td></tr>
						</table>';
		return $tableauHTML;
	}
	else{
		return "Vous n'êtes pas autorisé à accéder à cette page.";
		
	}
}

?>